{{- $root := . -}}
{{- range $name, $data := .Values.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ $root.Chart.Name }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
data:
{{- range $key, $value := $data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
---
{{- end }}
